language: erlang

otp_release:
  - 17.0

env:
  - ELIXIR_VSN=0.13.3
  - ELIXIR_VSN=0.14.3
  - ELIXIR_VSN=0.15.0

before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VSN/Precompiled.zip
  - unzip -qq Precompiled.zip -d elixir
  - export PATH=$PWD/elixir/bin:$PATH

install: mix deps.get
script: mix test --trace
