dist: trusty
sudo: false

language: elixir

matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 19.2
    - elixir: 1.4.5
      otp_release: 18.3
    - elixir: 1.4.5
      otp_release: 19.2
    - elixir: 1.4.5
      otp_release: 20.2
    - elixir: 1.5.3
      otp_release: 18.3
    - elixir: 1.5.3
      otp_release: 19.2
    - elixir: 1.5.3
      otp_release: 20.2
    - elixir: 1.6.1
      otp_release: 19.2
    - elixir: 1.6.1
      otp_release: 20.2
